# Generated by Django 5.2 on 2025-05-05 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("testsite", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=20, unique=True)),
                ("slug", models.SlugField(max_length=20, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name="transaction",
            name="transaction_date",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="transaction_type",
            field=models.CharField(
                choices=[("income", "Income"), ("expense", "Expense")], max_length=10
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="cat",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="category",
                to="testsite.category",
            ),
        ),
    ]
