# Generated by Django 5.2 on 2025-05-09 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("testsite", "0003_category_description_alter_transaction_cat"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "Category", "verbose_name_plural": "Categories"},
        ),
        migrations.AlterModelOptions(
            name="transaction",
            options={"ordering": ["-transaction_date"]},
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["-transaction_date"], name="testsite_tr_transac_8b9d32_idx"
            ),
        ),
    ]
