# Generated by Django 5.2.1 on 2025-05-14 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("testsite", "0002_alter_category_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(max_length=20, unique=True),
        ),
    ]
