# Generated by Django 5.2.1 on 2025-05-15 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("testsite", "0003_alter_category_slug"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ["pk"],
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
            },
        ),
    ]
