# Generated by Django 5.2.1 on 2025-05-15 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("testsite", "0005_alter_category_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="cat",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="transactions",
                to="testsite.category",
            ),
        ),
    ]
