# Generated by Django 5.2.1 on 2025-06-08 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("testsite", "0008_alter_category_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="is_base",
            field=models.BooleanField(default=False),
        ),
    ]
